spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    password: 1234
    username: c##player
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update					#sql 정의문 DDL 현재 create 이후 update로 변경할것.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #@Entity 어노테이션을 통해 클래스 그대로 DB를 만들경우 변수명 그대로 컬럼추가함.
      use-new-id-generator-mappings: false				#jpa가 가진 기본전략을 따라가지않겠다
    show-sql: true												#콘솔창에 sql문을 보일것인가
    properties:
      hibernate.format_sql: true								#콘솔창에 sql문 나열할때 정렬되어나온다.
      
  jackson:
    serialization:
      fail-on-empty-beans: false
    
server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      

